apiVersion: v1
kind: Service
metadata:
  name: kimai
  labels:
    app: kimai
spec:
  ports:
    - port: 8001
  selector:
    app: kimai
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai
  labels:
    app: kimai
spec:
  selector:
    matchLabels:
      app: kimai
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kimai
        tier: frontend
    spec:
      containers:
      - image: kimai/kimai2:apache
        name: kimai
        env:
        - name: ADMINMAIL
          value: admin@kimai.local
        - name: ADMINPASS
          value: changemeplease
        - name: DATABASE_URL
          value: mysql://kimaiuser:kimaipassword@kimai-mysql:3306/kimai
        - name: TRUSTED_HOSTS
          value: nginx,localhost,127.0.0.1,^(.+\.)?ap-south-1.elb.amazonaws.com$  
        ports:
        - containerPort: 8001
          name: kimai
        volumeMounts:
        - name: kimai-persistent-storage
          mountPath: /opt/kimai/var
      volumes:
      - name: kimai-persistent-storage
        persistentVolumeClaim:
          claimName: ebs-kimai
