apiVersion: v1
kind: Service
metadata:
  name: kimai-mysql
  labels:
    app: kimai
spec:
  ports:
    - port: 3306
  selector:
    app: kimai
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai-mysql
  labels:
    app: kimai
spec:
  selector:
    matchLabels:
      app: kimai
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kimai
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
        - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_DATABASE
          value: kimai
        - name: MYSQL_USER
          value: kimaiuser
        - name: MYSQL_PASSWORD
          value: kimaipassword
        - name: MYSQL_ROOT_PASSWORD
          value: changemeplease      
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ebs-mysql